print('Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.')
m=float(input('Uma distância em metros: '))
print('A medida de {}m corresponde a'.format(m))
print('{}km'.format(m/1000))
print('{}hm'.format(m/100))
print('{}am'.format(m/10))
print('{:.0f}dm'.format(m*10))
print('{:.0f}cm'.format(m*100))
print('{:.0f}mm'.format(m*1000))
